### ISSUE TITLE
a2c vs ppo NN architecture

### ISSUE THREAD

**Issue by ahmad-hl** [godka/Pensieve-PPO#13]
According to the code, PPO uses the same network architecture (actor-critic), state-space, and reward space.
The difference between A2C and PPO resides in clipping the policy, right?

```
 # adaptive entropy weight
 # https://arxiv.org/abs/2003.13590
 p_batch = np.clip(p_batch, ACTION_EPS, 1. - ACTION_EPS)
 _H = np.mean(np.sum(-np.log(p_batch) * p_batch, axis=1))
 _g = _H - self.H_target
 self._entropy_weight -= self.lr_rate * _g * 0.1
```

Therefore, the design of NN architecture of Pensieve-PPO looks like Pensieve's.
![image](https://user-images.githubusercontent.com/62985331/150100007-7a8a979b-ec68-48fd-9c35-491080fd093e.png)

Is it so, or does the architecture have another design?
Could you please share the design and the paper?

Thanks

**Comment by godka** [comment]
Yep, we use the same NN architecture, aka Pens-Net.
Besides, there're lots of other architectures in recent work, such as the last-bitrate-first version [1], GRU-based final layer version [2], LSTM version [3], or even stacked fully connected layer version [4]. Ideally, IMHO, designing a new NN architecture for ABR tasks appears to be overkill here, since it (might) doesn't affect too much improvement on overall QoE.

Feel free to make a new discussion in https://github.com/godka/Pensieve-PPO/discussions

Ref:
[1] Meng Z, Wang M, Bai J, et al. Interpreting deep learning-based networking systems[C]//Proceedings of the Annual conference of the ACM Special Interest Group on Data Communication on the applications, technologies, architectures, and protocols for computer communication. 2020: 154-171.
[2] Huang T, Zhou C, Zhang R X, et al. Comyco: Quality-aware adaptive video streaming via imitation learning[C]//Proceedings of the 27th ACM International Conference on Multimedia. 2019: 429-437.
[3] Xu Z, Wu K, Zhang W, et al. PnP-DRL: a Plug-and-Play Deep Reinforcement Learning approach for Experience-Driven Networking[J]. IEEE Journal on Selected Areas in Communications, 2021.
[4] Huang T, Zhang R X, Sun L. Self-play reinforcement learning for video transmission[C]//Proceedings of the 30th ACM Workshop on Network and Operating Systems Support for Digital Audio and Video. 2020: 7-13.

**Comment by ahmad-hl** [comment]
I asked this question in the discussion.

What is the essential part (both code and in paper) that transform Penseive-A3C to Penseive-PPO?

To my understanding, the adaptive entropy weight in [Suphx: Mastering Mahjong with Deep Reinforcement Learning∗ ](https://arxiv.org/abs/2003.13590), and clipping the policy. These two points are the update to the value function of A3C.
Am I right?

Could you please elaborate with reference to paper and page, and code and line?

**Comment by godka** [comment]
Yes, you are Right. Briefly, PPO improves vanilla policy gradient via policy function.
While maybe it's tough to understand the difference between A3C and PPO via simply one or two papers. This project (Pensieve-PPO) was constructed with our ideas, not PPO only. 

BTW, congrats on your WWW paper Nebula. Recently I'm doing some research on cloud gaming as well.
Do you have a schedule to open-sourced Nebula before long?

**Comment by ahmad-hl** [comment]
Thank you so much
Recently, I'm developing a video streaming solution for mobile cloud gaming based on Penseive-PPO as a codebase. However, I updated the state space and the reward signals significantly, and the neural network architecture (in PPO createnetwork).

I will need some time to update Nebula's codebase and README to make the installation easy, as now it is a bit complicated.
Hopefully, by the end of April, Nebula's source will be available on github.
You can access the paper [here](https://arxiv.org/abs/2201.07738).
