### ISSUE TITLE
A question about the comparing function "r" between new and old policies 

### ISSUE THREAD

**Issue by youngboy52** [godka/Pensieve-PPO#16]
I see the implementation of "r" function in your code https://github.com/godka/Pensieve-PPO/blob/a02918910bdf1c8eb3225460e4824df8f619edb3/src/ppo2.py#L62, and I realized that it is different from others which are shown as follows:
<img width="600" alt="9EEAB1D0F631746AD32E5A8A10B01668" src="https://user-images.githubusercontent.com/15629424/150295633-354f87b7-5d13-4072-bb0c-7b78da708e62.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/15629424/150295660-c3211ce6-c35b-4c4f-baa8-6ce4def0cd10.png">
The main difference is whether using the "exp", does it matter? Looking forward to your reply~

**Comment by godka** [comment]
Hi Yang,

We implement the PPO algorithm w.r.t the original paper, where the ratio is computed as ![](http://latex.codecogs.com/svg.latex?\frac{\pi_{new}}{\pi_{old}}).

Ideally, it is equal to the one you have posted.

![](http://latex.codecogs.com/svg.latex?\frac{\pi_{new}}{\pi_{old}}=e^{log\frac{\pi_{new}}{\pi_{old}}}=e^{log\pi_{new}-log\pi_{old})

The reason why they use log_prob instead of prob is the log_prob function has already been an API function in TF/PyTorch.

Best,
Tianchi
